### ISSUE TITLE
[Visual Bug] Sprinting in a chair

### ISSUE THREAD

**Issue by HacoKavanah** [chimericdream/minekea-fabric#29]
It is weird that I can actually sprint while sitting on a chair. Even weirder is the fact that I see the running particles. Btw, is it intentional I have to click it with an empty hand to sit in it? Inconvenient. :3

**Comment by chimericdream** [comment]
I agree that it's kind of weird. However, in my testing, I found the same behavior exists in a minecart that isn't on any rails. It is completely stationary, but the visual effects still trigger.

As for the empty hand thing; that will be fixed in the version coming later this week. I already have it updated in the main branch, so when I get things ported to 1.18.1 and 1.17.1 and finish squashing what bugs I can, it'll be uploaded to CurseForge.

**Comment by chimericdream** [comment]
2.5.1 of the mod has been published to CurseForge for all three supported versions!
