### ISSUE TITLE
Terracotta stairs and slabs bugged

### ISSUE THREAD

**Issue by JannekeJairia** [chimericdream/minekea-fabric#50]
When I try to either paint, or break the terracotta stairs or blocks it doesn't work. 
I've used different tools for breaking, none of which work. The breaking is obsidian level slow, and I don't get the block back. 

I am able to dye the terracotta blocks, but not the others, sadly.

**Comment by chimericdream** [comment]
At the moment, only full blocks can be dyed using the block painter, because of issues I ran into with copying complex block state data from other colored blocks. That said, I want to enhance the painter to allow painting more things, such as slabs, stairs, beds, etc.

As for the breaking issue, that's definitely a bug. Which version of Minecraft and Minekea are you on? From the sound of it, I may have missed adding those blocks to the relevant vanilla tool tag. If that's the case, it _should_ be a fairly quick fix. If not, I will have to do some more digging. But let's hope for the first scenario.

**Comment by chimericdream** [comment]
I just uploaded 2.8.3 and 3.1.2 of the mod for Minecraft 1.18.2 and 1.19, respectively. Everything should be working as expected now!

**Comment by JannekeJairia** [comment]
Sorry! didn't get a notification that you responded. 

I was on 2.8.2. Going to update and test it now :). thank you for fixing it!
