### ISSUE TITLE
[1.19] Barrels do not function as Villager POI's

### ISSUE THREAD

**Issue by xanthian** [chimericdream/minekea-fabric#64]
As per title.

Place any minekea barrel, spawn villager, watch him ignore it.
![image](https://user-images.githubusercontent.com/7688001/182111550-f21682d1-9bd0-44ea-90a2-08184f5f2d49.png)

**Comment by chimericdream** [comment]
I didn't even think to make them POIs for villagers, but that's a good point. I will see what needs to be done for these to work the same as a normal barrel.

Thanks for the report!

**Comment by xanthian** [comment]
BTW.
Interested to know how you do this, I have a barrel mod also and it was working in 1.18 but POI stuff got changed and doesn't work in 1.19 :(
For info, here's how I did it in 1.18
https://github.com/xanthian/variantbarrels/blob/1.18_archive/src/main/java/net/xanthian/variantbarrels/mixin/PointOfInterestTypeMixin.java

**Comment by chimericdream** [comment]
Sorry for the long delay on this. I have it fixed in dev and will push this out in the next release. If you haven't managed to get it working yourself yet, take a look at the Reinforced Barrels mod. Those barrels function as villager POIs, and my new code is almost completely copy/paste from theirs.

https://github.com/Aton-Kish/reinforced-barrels/blob/1.19/src/main/java/atonkish/reinfbarrel/world/poi/ModPointOfInterestTypes.java
https://github.com/Aton-Kish/reinforced-barrels/blob/1.19/src/main/java/atonkish/reinfbarrel/mixin/PointOfInterestTypesAccessor.java
